labels:
  environment: dev

statefulset:
  mysql-master:
    replicas: 1

    pod:
      nodeSelector:
        environment: dev

  mysql-slave:
    replicas: 2
    
    pod:
      nodeSelector:
        environment: dev

job:
  mysql-master:
    pod:
      nodeSelector:
        environment: dev