labels:
  environment: dev

statefulset:
  mysqlmaster:
    replicas: 1

    pod:
      nodeSelector:
        environment: dev

  mysqlslave:
    replicas: 1
    
    pod:
      nodeSelector:
        environment: dev

job:
  create_users:
    pod:
      nodeSelector:
        environment: dev

  insert_data:
    pod:
      nodeSelector:
        environment: dev