labels:
  environment: dev

statefulset:
  mysqlmaster:
    replicas: 1

    pod:
      nodeSelector:
        environment: dev

  mysqlslave:
    replicas: 2
    
    pod:
      nodeSelector:
        environment: dev

job:
  mysqlmaster:
    pod:
      nodeSelector:
        environment: dev