apiVersion: v1

kind: ConfigMap

metadata:
  name: {{ .Values.configMap.mysqlmaster.name }}
  labels:
{{ .Values.labels | toYaml | indent 4 }}

data:
{{ .Values.configMap.mysqlmaster.data | toYaml | indent 2 }}