name: Build and Deploy mysql database to Development

on:
  push:
    branches-ignore: main

jobs:
    prepare:
      runs-on: robot-shop-runner

    build:
      runs-on: robot-shop-runner

    deploy:
      runs-on: robot-shop-runner